register:
    path: /register
    controller: App\Controller\IndexController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\IndexController::api

login_check:
    path:     /login_check
    methods:  [POST]
